# Module - 1

# Pre-Processing

In [1]:
import pandas as p
import numpy as n

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
data=p.read_csv('softbug.csv')

In [4]:
data.head()

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,...,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount,defects
0,1.1,1.4,1.4,1.4,1.3,1.30,1.30,1.30,1.30,1.30,...,2,2,2,2,1.2,1.2,1.2,1.2,1.4,False
1,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.00,...,1,1,1,1,1,1,1,1,1,True
2,72.0,7.0,1.0,6.0,198.0,1134.13,0.05,20.31,55.85,23029.10,...,51,10,8,1,17,36,112,86,13,True
3,190.0,3.0,1.0,3.0,600.0,4348.76,0.06,17.06,254.87,74202.67,...,129,29,28,2,17,135,329,271,5,True
4,37.0,4.0,1.0,4.0,126.0,599.12,0.06,17.19,34.86,10297.30,...,28,1,6,0,11,16,76,50,7,True

In [5]:
data.shape

(10885, 22)

In [6]:
df=data.dropna()

In [ ]:
df.head(10)

In [7]:
df.shape

(10885, 22)

In [33]:
df.columns

Index(['loc', 'v(g)', 'ev(g)', 'iv(g)', 'n', 'v', 'l', 'd', 'i', 'e', 'b', 't',
       'lOCode', 'lOComment', 'lOBlank', 'locCodeAndComment', 'uniq_Op',
       'uniq_Opnd', 'total_Op', 'total_Opnd', 'branchCount', 'defects'],
      dtype='object')

In [9]:
df.isnull().sum()

loc                  0
v(g)                 0
ev(g)                0
iv(g)                0
n                    0
v                    0
l                    0
d                    0
i                    0
e                    0
b                    0
t                    0
lOCode               0
lOComment            0
lOBlank              0
locCodeAndComment    0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64

In [10]:
df.describe()

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,b,t,lOCode,lOComment,lOBlank,locCodeAndComment
count,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,10885.000000,1.088500e+04,10885.000000,1.088500e+04,10885.000000,10885.000000,10885.00000,10885.000000
mean,42.016178,6.348590,3.401047,4.001599,114.389738,673.758017,0.135335,14.177237,29.439544,3.683637e+04,0.224766,2.046465e+03,26.252274,2.737529,4.62554,0.370785
std,76.593332,13.019695,6.771869,9.116889,249.502091,1938.856196,0.160538,18.709900,34.418313,4.343678e+05,0.646408,2.413154e+04,59.611201,9.008608,9.96813,1.907969
min,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.00000,0.000000
25%,11.000000,2.000000,1.000000,1.000000,14.000000,48.430000,0.030000,3.000000,11.860000,1.619400e+02,0.020000,9.000000e+00,4.000000,0.000000,0.00000,0.000000
50%,23.000000,3.000000,1.000000,2.000000,49.000000,217.130000,0.080000,9.090000,21.930000,2.031020e+03,0.070000,1.128300e+02,13.000000,0.000000,2.00000,0.000000
75%,46.000000,7.000000,3.000000,4.000000,119.000000,621.480000,0.160000,18.900000,36.780000,1.141643e+04,0.210000,6.342500e+02,28.000000,2.000000,5.00000,0.000000
max,3442.000000,470.000000,165.000000,402.000000,8441.000000,80843.080000,1.300000,418.200000,569.780000,3.107978e+07,26.950000,1.726655e+06,2824.000000,344.000000,447.00000,108.000000

In [12]:
df.lOBlank.unique()

array([  2,   1,   8,  28,   6,   5,   0,  16,  17,  14,  13,   7,  26,
        23,   9,   3,   4,  19,  12,  15,  24,  10,  37,  11,  31,  73,
        21,  20,  29,  47,  52,  34,  18,  27,  33,  38,  76,  75,  25,
        30,  79,  32,  22,  58,  45,  89,  49,  84,  43,  59,  44,  40,
        39,  78,  36,  66,  61,  55,  63,  83,  35,  54,  74,  51,  64,
       102,  80,  69,  42, 135, 114,  93, 143,  53,  88,  67, 202, 106,
        56, 105, 164, 101, 447,  72,  41,  46,  50,  86,  70, 129, 219,
        48,  65,  92, 154], dtype=int64)

In [13]:
df.lOComment.unique()

array([  2,   1,  10,  29,   0,  92,  13,  41,  11,  19,   4,   6,   7,
         3,   9,  21,   8,  17,  28,  14,  23,  31,  24,  72,   5,  35,
        43,  15,  32,  18,  37,  12,  55, 130,  34,  40,  45,  69,  16,
        39,  25, 107,  20,  22,  65,  36,  81,  30,  33,  66,  46,  44,
        56,  60,  98,  82,  27,  42,  96,  91,  85,  38,  74,  68,  86,
        26,  73,  51, 120,  47, 206,  49,  78, 344,  58,  75, 157,  54,
        67, 141,  93,  61, 112,  94,  57,  63,  59, 162], dtype=int64)

In [14]:
df.locCodeAndComment.unique()

array([  2,   1,   0,   6,   5,  22,   3,   8,  12,   4,   7,  16,  11,
         9,  10,  13,  30,  38, 108,  14,  20,  23,  34,  17,  42,  18,
        24,  15,  21,  28], dtype=int64)

In [15]:
df.uniq_Op.unique()

array(['1.2', '1', '17', '11', '14', '0', '4', '19', '32', '7', '26',
       '27', '21', '9', '28', '22', '16', '8', '20', '10', '13', '25',
       '12', '5', '34', '15', '6', '18', '24', '30', '?', '23', '3', '38',
       '29', '33', '39', '45', '31', '58', '37', '49', '48', '410', '35',
       '36', '42', '40', '46', '44', '41', '52', '74', '280', '65', '73',
       '61', '78', '172', '105', '102', '98', '411', '155', '2', '55',
       '43', '47', '99'], dtype=object)

In [16]:
df.defects.unique()

array([False,  True])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10885 entries, 0 to 10884
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   loc                10885 non-null  float64
 1   v(g)               10885 non-null  float64
 2   ev(g)              10885 non-null  float64
 3   iv(g)              10885 non-null  float64
 4   n                  10885 non-null  float64
 5   v                  10885 non-null  float64
 6   l                  10885 non-null  float64
 7   d                  10885 non-null  float64
 8   i                  10885 non-null  float64
 9   e                  10885 non-null  float64
 10  b                  10885 non-null  float64
 11  t                  10885 non-null  float64
 12  lOCode             10885 non-null  int64
 13  lOComment          10885 non-null  int64
 14  lOBlank            10885 non-null  int64
 15  locCodeAndComment  10885 non-null  int64
 16  uniq_Op            10885 non-null  object
 17  uniq_Opnd          10885 non-null  object
 18  total_Op           10885 non-null  object
 19  total_Opnd         10885 non-null  object
 20  branchCount        10885 non-null  object
 21  defects            10885 non-null  bool
dtypes: bool(1), float64(12), int64(4), object(5)
memory usage: 1.8+ MB

In [18]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
10880    False
10881    False
10882    False
10883    False
10884    False
Length: 10885, dtype: bool

In [19]:
sum(df.duplicated())

1973

In [20]:
df.corr()

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,b,t,lOCode,lOComment,lOBlank,locCodeAndComment,defects
loc,1.000000,0.817757,0.517551,0.784057,0.881795,0.900293,-0.286587,0.689543,0.499946,0.750564,0.899965,0.750564,0.921918,0.612858,0.803573,0.278119,0.245388
v(g),0.817757,1.000000,0.701710,0.859590,0.730781,0.759881,-0.252902,0.669057,0.303031,0.709501,0.759635,0.709501,0.799915,0.384506,0.538366,0.209811,0.208644
ev(g),0.517551,0.701710,1.000000,0.639574,0.465992,0.445902,-0.233982,0.434009,0.213211,0.315538,0.445693,0.315538,0.454604,0.294208,0.338243,0.190911,0.172973
iv(g),0.784057,0.859590,0.639574,1.000000,0.702415,0.743193,-0.197736,0.575369,0.309717,0.757702,0.743013,0.757702,0.775873,0.351583,0.541296,0.207028,0.181984
n,0.881795,0.730781,0.465992,0.702415,1.000000,0.984276,-0.240749,0.808113,0.651209,0.716536,0.983938,0.716536,0.944383,0.596374,0.798561,0.284391,0.204143
v,0.900293,0.759881,0.445902,0.743193,0.984276,1.000000,-0.198104,0.752206,0.598743,0.800000,0.999696,0.800000,0.962078,0.576844,0.792330,0.266537,0.189136
l,-0.286587,-0.252902,-0.233982,-0.197736,-0.240749,-0.198104,1.000000,-0.347215,-0.166801,-0.062026,-0.196147,-0.062026,-0.218373,-0.165885,-0.223670,-0.106117,-0.164917
d,0.689543,0.669057,0.434009,0.575369,0.808113,0.752206,-0.347215,1.000000,0.398162,0.574298,0.751835,0.574298,0.768188,0.502121,0.637211,0.253793,0.169629
i,0.499946,0.303031,0.213211,0.309717,0.651209,0.598743,-0.166801,0.398162,1.000000,0.209268,0.598341,0.209268,0.563920,0.392551,0.572352,0.217810,0.192831
e,0.750564,0.709501,0.315538,0.757702,0.716536,0.800000,-0.062026,0.574298,0.209268,1.000000,0.799868,1.000000,0.809070,0.384806,0.600649,0.148693,0.086036
b,0.899965,0.759635,0.445693,0.743013,0.983938,0.999696,-0.196147,0.751835,0.598341,0.799868,1.000000,0.799868,0.961779,0.576678,0.792081,0.266720,0.189342
t,0.750564,0.709501,0.315538,0.757702,0.716536,0.800000,-0.062026,0.574298,0.209268,1.000000,0.799868,1.000000,0.809070,0.384806,0.600649,0.148693,0.086036
lOCode,0.921918,0.799915,0.454604,0.775873,0.944383,0.962078,-0.218373,0.768188,0.563920,0.809070,0.961779,0.809070,1.000000,0.553121,0.807319,0.259133,0.195897
lOComment,0.612858,0.384506,0.294208,0.351583,0.596374,0.576844,-0.165885,0.502121,0.392551,0.384806,0.576678,0.384806,0.553121,1.000000,0.620149,0.262013,0.160887
lOBlank,0.803573,0.538366,0.338243,0.541296,0.798561,0.792330,-0.223670,0.637211,0.572352,0.600649,0.792081,0.600649,0.807319,0.620149,1.000000,0.270338,0.199644
locCodeAndComment,0.278119,0.209811,0.190911,0.207028,0.284391,0.266537,-0.106117,0.253793,0.217810,0.148693,0.266720,0.148693,0.259133,0.262013,0.270338,1.000000,0.117891
defects,0.245388,0.208644,0.172973,0.181984,0.204143,0.189136,-0.164917,0.169629,0.192831,0.086036,0.189342,0.086036,0.195897,0.160887,0.199644,0.117891,1.000000

In [34]:
df.columns

Index(['loc', 'v(g)', 'ev(g)', 'iv(g)', 'n', 'v', 'l', 'd', 'i', 'e', 'b', 't',
       'lOCode', 'lOComment', 'lOBlank', 'locCodeAndComment', 'uniq_Op',
       'uniq_Opnd', 'total_Op', 'total_Opnd', 'branchCount', 'defects'],
      dtype='object')

In [21]:
df['defects'].value_counts()

False    8779
True     2106
Name: defects, dtype: int64

In [26]:
print("Minimum value of lOCode is:", df.lOCode.min())
print("Maximum value of lOCode is:", df.lOCode.max())

Minimum value of lOCode is: 0
Maximum value of lOCode is: 2824

In [27]:
print("Minimum value of lOComment is:", df.lOComment.min())
print("Maximum value of lOComment is:", df.lOComment.max())

Minimum value of lOComment is: 0
Maximum value of lOComment is: 344

In [28]:
print("Minimum value of lOBlank is:", df.lOBlank.min())
print("Maximum value of lOBlank is:", df.lOBlank.max())

Minimum value of lOBlank is: 0
Maximum value of lOBlank is: 447

In [29]:
print("Minimum value of locCodeAndCommen is:", df.locCodeAndComment.min())
print("Maximum value of locCodeAndCommen is:", df.locCodeAndComment.max())

Minimum value of locCodeAndCommen is: 0
Maximum value of locCodeAndCommen is: 108

In [30]:
p.crosstab(df.defects,df.lOBlank)

lOBlank,0,1,2,3,4,5,6,7,8,9,...,106,114,129,135,143,154,164,202,219,447
defects,,,,,,,,,,,,,,,,,,,,,
False,2812,1322,993,906,655,492,251,245,179,144,...,0,0,1,0,0,1,0,0,1,0
True,457,108,186,174,162,140,106,72,78,77,...,1,1,0,1,1,0,1,1,0,1

In [31]:
p.Categorical(df['defects']).describe()

            counts     freqs
categories
False         8779  0.806523
True          2106  0.193477

In [32]:
df.head(10)

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,...,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount,defects
0,1.1,1.4,1.4,1.4,1.3,1.30,1.30,1.30,1.30,1.30,...,2,2,2,2,1.2,1.2,1.2,1.2,1.4,False
1,1.0,1.0,1.0,1.0,1.0,1.00,1.00,1.00,1.00,1.00,...,1,1,1,1,1,1,1,1,1,True
2,72.0,7.0,1.0,6.0,198.0,1134.13,0.05,20.31,55.85,23029.10,...,51,10,8,1,17,36,112,86,13,True
3,190.0,3.0,1.0,3.0,600.0,4348.76,0.06,17.06,254.87,74202.67,...,129,29,28,2,17,135,329,271,5,True
4,37.0,4.0,1.0,4.0,126.0,599.12,0.06,17.19,34.86,10297.30,...,28,1,6,0,11,16,76,50,7,True
5,31.0,2.0,1.0,2.0,111.0,582.52,0.08,12.25,47.55,7135.87,...,19,0,5,0,14,24,69,42,3,True
6,78.0,9.0,5.0,4.0,0.0,0.00,0.00,0.00,0.00,0.00,...,0,0,0,0,0,0,0,0,17,True
7,8.0,1.0,1.0,1.0,16.0,50.72,0.36,2.80,18.11,142.01,...,5,0,1,0,4,5,9,7,1,True
8,24.0,2.0,1.0,2.0,0.0,0.00,0.00,0.00,0.00,0.00,...,0,0,0,0,0,0,0,0,3,True
9,143.0,22.0,20.0,10.0,0.0,0.00,0.00,0.00,0.00,0.00,...,0,0,0,0,0,0,0,0,43,True

In [35]:
df.columns

Index(['loc', 'v(g)', 'ev(g)', 'iv(g)', 'n', 'v', 'l', 'd', 'i', 'e', 'b', 't',
       'lOCode', 'lOComment', 'lOBlank', 'locCodeAndComment', 'uniq_Op',
       'uniq_Opnd', 'total_Op', 'total_Opnd', 'branchCount', 'defects'],
      dtype='object')

In [36]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['loc', 'v(g)', 'ev(g)', 'iv(g)', 'n', 'v', 'l', 'd', 'i', 'e', 'b', 't',
       'lOCode', 'lOComment', 'lOBlank', 'locCodeAndComment', 'uniq_Op',
       'uniq_Opnd', 'total_Op', 'total_Opnd', 'branchCount', 'defects']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [41]:
df.head(9)

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,...,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount,defects
0,1,1,1,1,2,2,54,2,2,2,...,2,2,2,2,2,2,2,2,1,0
1,0,0,0,0,1,1,53,1,1,1,...,1,1,1,1,1,1,1,1,0,1
2,72,7,0,6,199,2553,5,1165,3178,5249,...,51,10,8,1,13,96,37,445,21,1
3,188,3,0,3,549,3735,6,951,4234,6250,...,129,29,28,2,13,36,291,204,99,1
4,37,4,0,4,127,1590,6,958,2071,4198,...,28,1,6,0,6,54,525,349,119,1
5,31,2,0,2,112,1553,8,624,2820,3681,...,19,0,5,0,9,77,503,313,70,1
6,78,9,4,4,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,43,1
7,8,0,0,0,17,58,36,29,751,112,...,5,0,1,0,40,112,559,411,0,1
8,24,2,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,70,1